import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1280, height: 1500 } });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
p.on('console', m => { if (m.type()==='error' && !m.text().includes('favicon')) errs.push('CONSOLE ' + m.text()); });
await p.goto('http://localhost:4174/', { waitUntil: 'networkidle' });
await p.screenshot({ path: '/tmp/f-children.png' });
await p.getByRole('tab', { name: /The brain/ }).click(); await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/f-brain.png' });
await p.getByRole('tab', { name: /Five children/ }).click(); await p.waitForTimeout(400);
await p.locator('button.btn.ghost', { hasText: 'Read the trace' }).nth(2).click();
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/f-trace.png' });
console.log(errs.length ? errs.join('\n') : 'clean');
await b.close();
